name = "app"
compatibility_date = "2026-06-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "quesarave"
database_id = "5a9bfdf4-7214-44b6-a25b-6130ffb94dfa"
